### ISSUE TITLE
Torchmaster (torchmaster) has failed to load correctly

### ISSUE THREAD

**Issue by tetrayon** [Xalcon/TorchMaster#163]
-- MOD torchmaster --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/block/Block
		at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?] {}
		at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?] {}
		at java.lang.Class.getDeclaredConstructor(Class.java:2691) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.67.jar%2366!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.67.jar%2365!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: torchmaster-2.3.8.jar
	Failure message: Torchmaster (torchmaster) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraft/block/Block
	Mod Version: 2.3.8
	Mod Issue URL: https://github.com/Xalcon/TorchMaster/issues/
	Exception message: java.lang.ClassNotFoundException: net.minecraft.block.Block
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.46.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.46.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?] {}
	at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructor(Class.java:2691) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.67.jar%2366!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.67.jar%2365!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

**Comment by Xalcon** [comment]
You are doing it wrong.
Torchmaster Version 2.3.8 ist for Minecraft 1.16
Use Torchmaster 3.0+ for 1.17

**Comment by tetrayon** [comment]
I'll try 3.0+. Thank you

**Comment by tetrayon** [comment]
Yeah, that works.
