### ISSUE TITLE
[Bug]: Game seems to crash when a warden tries to spawn

### ISSUE THREAD

**Issue by BLU3NINJ4** [Xalcon/TorchMaster#239]
### Torchmaster Version

21.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.16.2-1.21

### What happened?

Im not sure what causes the crash my friend told me they where in an ancient city and triggered a warden spawn 2 times when the server crashed
Im not sure if its the torchmaster mod or something else but the mod is the only thing i see in the crash log 
unless im missing something

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-09-25 01:55:19
Description: Exception ticking world

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_7244 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_7133.method_43148(class_7133.java:206)
	at net.minecraft.class_7133.method_43147(class_7133.java:181)
	at net.minecraft.class_7268.method_43132(class_7268.java:87)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at net.minecraft.class_7268.method_9588(class_7268.java:87)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1149)
	at net.minecraft.class_3218.method_14189(class_3218.java:759)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [torchmaster.fabric.mixins.json:SpawnUtilMixin from mod torchmaster] from phase [DEFAULT] in config [torchmaster.fabric.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: non-static callback method net/minecraft/class_7244::torchmaster_trySpawnMob_checkSpawnRules targets a static method which is not supported [INJECT_APPLY Applicator Phase -> torchmaster.fabric.mixins.json:SpawnUtilMixin from mod torchmaster -> Apply Injections ->  -> Inject -> torchmaster.fabric.mixins.json:SpawnUtilMixin from mod torchmaster->@Redirect::torchmaster_trySpawnMob_checkSpawnRules(Lnet/minecraft/class_1308;Lnet/minecraft/class_1936;Lnet/minecraft/class_3730;)Z]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:371)
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetForNode(Injector.java:416)
	at org.spongepowered.asm.mixin.injection.invoke.RedirectInjector.inject(RedirectInjector.java:332)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:284)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:508)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1483)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more
```

**Comment by Xalcon** [comment]
Jep, that looks like a bug on my side. Currently at work, so the fix will have to wait a few hours. Thanks for reporting.

**Comment by Xalcon** [comment]
I've published updates to fix this issue:
* Torchmaster 21.0.3 for MC 1.21
* Torchmaster 21.1.2 for MC 1.21.1
