### ISSUE TITLE
minecraft 1.14.4 crash on client open 

### ISSUE THREAD

**Issue by raziel23x** [Xalcon/TorchMaster#94]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/30/19 2:47 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.direwolf20.buildinggadgets.common.registry.objects.BuildingObjects.initColorHandlers(BuildingObjects.java:33) ~[?:3.0.0] {}
	at com.direwolf20.buildinggadgets.common.BuildingGadgets$$Lambda$2954/1323378868.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2040/1901371976.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:163) ~[?:28.0] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$28(ModLoader.java:238) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader$$Lambda$3659/280597866.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:209) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:238) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:196) ~[?:?] {}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:501) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.24.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$345/883862737.call(Unknown Source) [forge-1.14.4-28.0.24.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.direwolf20.buildinggadgets.common.registry.objects.BuildingObjects.initColorHandlers(BuildingObjects.java:33)
	at com.direwolf20.buildinggadgets.common.BuildingGadgets$$Lambda$2954/1323378868.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2040/1901371976.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:163)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$28(ModLoader.java:238)
	at net.minecraftforge.fml.ModLoader$$Lambda$3659/280597866.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:209)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:238)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:196)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:501)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$345/883862737.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 382908392 bytes (365 MB) / 3740794880 bytes (3567 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 3.1.0+58+1395384
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.24
	FML Language Providers: 
		javafml@28.0
		kotori_scala@2.12.8
	Mod List: 
		A+Block+of+Charcoal-1.2.jar A Block of Charcoal {charcoalblock@1.2 COMMON_SETUP}
		angelblock-1.0.jar Angel Block {angelblock@1.0 COMMON_SETUP}
		Apotheosis-1.14.4-2.1.0.jar Apotheosis {apotheosis@2.1.0 COMMON_SETUP}
		AppleSkin-mc1.14.3-forge-1.0.11.jar AppleSkin {appleskin@1.0.11 COMMON_SETUP}
		bambooeverything-1.14-1.0.jar Bamboo Everything {bambooeverything@1.14-1.0 COMMON_SETUP}
		BetterCrates-1.14.4-1.0.0.jar Better Crates {bettercrates@1.0.0 COMMON_SETUP}
		BiomesOPlenty-1.14.4-9.0.0.195-universal.jar Biomes O' Plenty {biomesoplenty@version COMMON_SETUP}
		buildinggadgets-3.0.0.jar Building Gadgets {buildinggadgets@version CREATE_REGISTRIES}
		bwncr-1.14.4-3.5.10.jar Bad Wither No Cookie Reloaded {bwncr@1.14.4-3.5.10 CREATE_REGISTRIES}
		caelus-FORGE-1.14.4-0.10.jar Caelus API {caelus@FORGE-1.14.4-0.10 COMMON_SETUP}
		ChineseWorkshop-1.14.4-2.3.0.jar ChineseWorkshop {chineseworkshop@2.3.0 COMMON_SETUP}
		ChunkNoGoByeBye-1.14.4-1.0.2.jar ChunkNoGoByeBye {chunknogobyebye@1.14.4-1.0.2 COMMON_SETUP}
		compressed_items-1.14.4-1.0.jar Compressed Items {compressed_items@1.14.4-1.0 COMMON_SETUP}
		corail_woodcutter-1.0.2-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.0.2 COMMON_SETUP}
		craftingstation-2.0.0.jar Crafting Station {craftingstation@2.0.0 COMMON_SETUP}
		Cucumber-1.14.4-2.0.0.jar Cucumber Library {cucumber@2.0.0 COMMON_SETUP}
		curios-FORGE-1.14.4-0.18.jar Curios API {curios@FORGE-1.14.4-0.18 COMMON_SETUP}
		curiouselytra-FORGE-1.14.4-0.7.jar Curious Elytra {curiouselytra@FORGE-1.14.4-0.7 COMMON_SETUP}
		curiousshulkerboxes-FORGE-1.14.4-0.7.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.14.4-0.7 COMMON_SETUP}
		DefaultSettings-1.14.4-1.3.2.jar DefaultSettings {defaultsettings@1.3.2 CREATE_REGISTRIES}
		ElementaryOres-1.14.4-0.0.1.jar Elementary Ores {elementaryores@1.14.4-0.0.1 CREATE_REGISTRIES}
		ElevatorMod-1.14.4-1.3.11.jar Elevator Mod {elevatorid@1.14.4-1.3.11 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.14.4-1.3.3.jar EnchantmentDescriptions {enchdesc@1.3.3 COMMON_SETUP}
		ender_compass-2.2.1.jar Ender Compass {ender_compass@2.2.1 COMMON_SETUP}
		EnderBags-1.14.4-4.1.0.jar Ender Bags {ender_bags@4.1.0 COMMON_SETUP}
		EnderMagnet-1.14.3-1.0.0.jar Ender Magnet {endermagnet@1.14.3-1.0.0 COMMON_SETUP}
		essentials-1.14.4-2.3.1.jar Essentials {essentials@1.14.4-2.3.1 COMMON_SETUP}
		FastLeafDecay-v16.jar FastLeafDecay {fastleafdecay@v16 COMMON_SETUP}
		firstaid-1.7.6.jar First Aid {firstaid@1.7.6 COMMON_SETUP}
		fishtraps-0.0.4.jar Fish Traps {fishtraps@1.14.4-0.0.4 COMMON_SETUP}
		FleshToLeather-1.14.3-1.1.0.jar FleshToLeather {fleshtoleather@1.1.0 COMMON_SETUP}
		forbidden_arcanus-1.14.4-1.0-Beta-1.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.0-Beta-1 COMMON_SETUP}
		forgemod_VoxelMap-1.9.13_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 COMMON_SETUP}
		FpsReducer-mc1.14.4-1.12.4.jar FPS Reducer {fpsreducer@mc1.14.4-1.12.4 COMMON_SETUP}
		FTBUtilitiesBackups-2.0.0.7.jar FTB Utilities: Backups {ftbbackups@2.0.0.7 COMMON_SETUP}
		furniture-7.0.0-pre3-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre3 COMMON_SETUP}
		GemsPlusPlus -1.14.4-0.1.0.jar GemsPlusPlus {gemsplusplus@0.1.0 COMMON_SETUP}
		globaldatapack-1.14.4-1.1.jar Dark Roleplay - Global Datapacks {drpglobaldatapack@1.14.4-1.1 COMMON_SETUP}
		globalxp-1.14.4-v1.4.5.jar Global XP {globalxp@v1.4.5 COMMON_SETUP}
		Gobber2-1.14.4-2.1.72.jar Gobber 2 {gobber2@2.1.72 COMMON_SETUP}
		gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 COMMON_SETUP}
		Hwyla-forge-1.10.4-B65_1.14.2.jar Waila {waila@version COMMON_SETUP}
		inventorysorter-1.14.4-15.2.0.jar Simple Inventory Sorter {inventorysorter@15.2.0 COMMON_SETUP}
		ironchest-1.14.3-9.0.DEV.55a7af2.jar Iron Chests {ironchest@1.14.3-9.0.DEV.55a7af2 COMMON_SETUP}
		jei-1.14.3-6.0.0.8.jar Just Enough Items {jei@6.0.0.8 COMMON_SETUP}
		Kiwi-1.14.3-2.2.5.jar Kiwi {kiwi@2.2.5 COMMON_SETUP}
		KleeSlabs_1.14.3-7.4.6.jar KleeSlabs {kleeslabs@7.4.6 COMMON_SETUP}
		LargeFluidTank-14.6.6.jar FluidTank {fluidtank@14.6.6 COMMON_SETUP}
		LightOverlay-3.3.1.jar Light Overlay Forge {lightoverlay-forge@3.3.1 COMMON_SETUP}
		lycanitesmobs-1.14.4-2.1.0.0-beta12.jar Lycanites Mobs {lycanitesmobs@1.0 CONSTRUCT}
		mcjtylib-1.14-3.5.5-alpha.jar McJtyLib {mcjtylib@NONE COMMON_SETUP}
		metalbarrels-1.3b.jar Metal Barrels {metalbarrels@1.3b COMMON_SETUP}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 COMMON_SETUP}
		moreboots-1.1.4.jar More Boots {moreboots@1.1.4 COMMON_SETUP}
		moreprog-1.14.4-0.3.4.jar MoreProgression {moreprogression@0.3.4 COMMON_SETUP}
		Overloaded-1.14.4-0.0.70.jar Overloaded {overloaded@1.14.4-0.0.70 COMMON_SETUP}
		overloadedarmorbar-3.0.0.jar Example Mod {overloadedarmorbar@3.0.0 COMMON_SETUP}
		PickleTweaks-1.14.4-3.0.1.jar Pickle Tweaks {pickletweaks@3.0.1 COMMON_SETUP}
		Placebo-1.14.4-2.1.1.jar Placebo {placebo@2.1.1 COMMON_SETUP}
		Portality-1.14.4-2.0.12.jar Portality {portality@NONE COMMON_SETUP}
		practicaltools-1.14.4-1.3b.jar Practical Tools {practicaltools@1.14.4-1.3b COMMON_SETUP}
		PyramidPlunder-1.14.4-1.0.jar Pyramid Plunder {pyramidplunder@1.14.4-1.0 COMMON_SETUP}
		randompatches-1.14.4-1.17.3.0.jar RandomPatches {randompatches@1.14.4-1.17.3.0 COMMON_SETUP}
		reap-1.10.0.jar Reap Mod {reap@1.10.0 COMMON_SETUP}
		rftoolsbase-1.14-0.0.2-alpha.jar RFToolsBase {rftoolsbase@NONE COMMON_SETUP}
		rftoolspower-1.14-1.2.2-alpha.jar RFToolsPower {rftoolspower@NONE COMMON_SETUP}
		RingOfAttraction-1.0.0.jar Ring of Attraction {ring_of_attraction@1.0.0 COMMON_SETUP}
		RingOfBlink-1.0.4.jar Ring of Blink {ring_of_blink@1.0.4 COMMON_SETUP}
		RingOfEnderchest-1.0.2.jar Ring of Enderchest {ring_of_enderchest@1.0.2 COMMON_SETUP}
		RingOfGrowth-1.0.4.jar Ring of Growth {ring_of_growth@1.0.4 COMMON_SETUP}
		RingOfMiner-1.0.1.jar Ring of Miner {ring_of_miner@1.0.0 COMMON_SETUP}
		RingOfRepair-1.0.3.jar Ring of Repair {ring_of_repair@1.0.3 COMMON_SETUP}
		RingOfTeleport-1.0.3.jar Ring of Teleport {ring_of_teleport@1.0.3 COMMON_SETUP}
		rsgauges-1.14.4-1.1.5-b1.jar Redstone Gauges and Switches {rsgauges@1.1.5-b1 COMMON_SETUP}
		Sauuuuucey's Ores-1.14.4-1.3-release.jar Sauuuuucey's Ores {sauuuuuceysores@1.3-release COMMON_SETUP}
		Sauuuuucey's+Farming-1.14.3-1.0-beta.jar Sauuuuucey's Farming {sauuuuuceysfarming@1.0-beta COMMON_SETUP}
		ServerTabInfo-1.14.4-1.2.5-beta.jar Server Tab Info {servertabinfo@1.2.5-beta COMMON_SETUP}
		SilentGear-1.14.4-1.3.2+51.jar Silent Gear {silentgear@1.3.2+51 COMMON_SETUP}
		SilentGems-1.14.4-3.3.1+56.jar Silent's Gems 3 {silentgems@3.3.1+56 COMMON_SETUP}
		SilentLib-1.14.4-4.3.0+38.jar Silent Lib {silentlib@4.3.0+38 COMMON_SETUP}
		simplefarming-1.14.4-1.0.6.jar Simple Farming {simplefarming@1.14.4-1.0.6 COMMON_SETUP}
		simpleores-1.14.4-2.0.6.0.jar Simple Ores {simpleores@1.14.4-2.0.6.0 COMMON_SETUP}
		SimpleStorageNetwork-1.14.4-0.0.8.jar Simple Storage Network {storagenetwork@1.14.4-0.0.8 COMMON_SETUP}
		simplylight-1.14.4-0.8.0.jar Simply Light {simplylight@1.14.4-0.8.0 COMMON_SETUP}
		StoneChest-1.14.4-1.0.1.jar Stone Chest {stonechest@1.0.1 COMMON_SETUP}
		StoneCraftingTable-1.14.2-1.0.3.jar Stone Crafting Table {sct@1.0.3 COMMON_SETUP}
		SuperTools-1.2c.jar Super Tools {supertools@1.2c COMMON_SETUP}
		theoneprobe-1.14-1.4.32-alpha.jar The One Probe {theoneprobe@NONE COMMON_SETUP}
		theplopper-1.14.4-v1.2.2.jar The Plopper {theplopper@v1.2.2 COMMON_SETUP}
		titanium-2.1.53.jar Titanium {titanium@2.1.53 COMMON_SETUP}
		ToolBelt-1.14.4-1.9.10.jar Tool Belt {toolbelt@1.9.10 COMMON_SETUP}
		TorchBandolier-1.14.4-1.3.1+6.jar Torch Bandolier {torchbandolier@1.3.1+6 COMMON_SETUP}
		torchmaster-2.0.0.3-alpha.jar Torchmaster {torchmaster@2.0.0.3-alpha CONSTRUCT}
		toughnessbar-4.0.jar Toughness Bar {toughnessbar@4.0 CONSTRUCT}
		u_team_core-1.14.4-2.6.1.126.jar U Team Core {uteamcore@2.6.1.126 COMMON_SETUP}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 COMMON_SETUP}
		WaterStrainer-1.14.4-7.0.0.jar Water Strainer {waterstrainer@1.14.4-7.0.0 COMMON_SETUP}
		weapon_craftery-1.14.4-1.0-Beta-2.jar Weapon Craftery {weapon_craftery@1.14.4-1.0-Beta-2 CONSTRUCT}
		wetstone-1.1.2.jar Wetstone {wetstone@1.1.2 CONSTRUCT}
		WoolToString-1.14.2-1.0.0.jar WoolToString {wooltostring@1.0.0 CONSTRUCT}
		wrenchest-1.14.x-v1.0.jar Wrenchest {wrenchest@v1.0 CONSTRUCT}
		XL-Food-Mod-1.14.4-2.0.3.jar XL Food Mod {xlfoodmod@2.0.3 CONSTRUCT}
		YAMDA-4.0.0.jar YAMDA {yamda@4.0.0 CONSTRUCT}
		forge-1.14.4-28.0.24-universal.jar Forge {forge@28.0.24 CONSTRUCT}
	Launched Version: forge-28.0.24
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Soartex_Fanver.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by Xalcon** [comment]
Ok? What do you want me to do? O.o
This is the torchmaster repository. You crash seems to be related to building gadgets.

**Comment by raziel23x** [comment]
oops wrong crash report
let me regenerate the new one and update the op with it

**Comment by raziel23x** [comment]
whelp it that was the correct crash report it only crashes when torchmaster is enabled as soon as i remove the torchmaster jar file it crashes and gives that report

**Comment by Xalcon** [comment]
I've done another build but compiled against the latest forge release. It seems there was an issue, not sure if its related.
The release will be available on curseforge once they approved it.

**Comment by raziel23x** [comment]
yeah it seems the last few forge builds seems to be breaking previous builds for many mods
